package com.example.school_system.demo.pojo;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_name
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    private String courseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.teacher_name
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    private String teacherName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.class_hour
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    private String classHour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.teach_class_hour
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    private String teachClassHour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.computer_class_hour
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    private String computerClassHour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.class_type
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    private String classType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.major_name
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    private String majorName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_name
     *
     * @return the value of course.course_name
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_name
     *
     * @param courseName the value for course.course_name
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.teacher_name
     *
     * @return the value of course.teacher_name
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.teacher_name
     *
     * @param teacherName the value for course.teacher_name
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName == null ? null : teacherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.class_hour
     *
     * @return the value of course.class_hour
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public String getClassHour() {
        return classHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.class_hour
     *
     * @param classHour the value for course.class_hour
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public void setClassHour(String classHour) {
        this.classHour = classHour == null ? null : classHour.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.teach_class_hour
     *
     * @return the value of course.teach_class_hour
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public String getTeachClassHour() {
        return teachClassHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.teach_class_hour
     *
     * @param teachClassHour the value for course.teach_class_hour
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public void setTeachClassHour(String teachClassHour) {
        this.teachClassHour = teachClassHour == null ? null : teachClassHour.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.computer_class_hour
     *
     * @return the value of course.computer_class_hour
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public String getComputerClassHour() {
        return computerClassHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.computer_class_hour
     *
     * @param computerClassHour the value for course.computer_class_hour
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public void setComputerClassHour(String computerClassHour) {
        this.computerClassHour = computerClassHour == null ? null : computerClassHour.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.class_type
     *
     * @return the value of course.class_type
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public String getClassType() {
        return classType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.class_type
     *
     * @param classType the value for course.class_type
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public void setClassType(String classType) {
        this.classType = classType == null ? null : classType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.major_name
     *
     * @return the value of course.major_name
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public String getMajorName() {
        return majorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.major_name
     *
     * @param majorName the value for course.major_name
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public void setMajorName(String majorName) {
        this.majorName = majorName == null ? null : majorName.trim();
    }
}