package com.example.school_system.demo.pojo;

public class MajorClass extends MajorClassKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_class.people_num
     *
     * @mbg.generated Sat May 04 18:49:00 CST 2019
     */
    private String peopleNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_class.major_name
     *
     * @mbg.generated Sat May 04 18:49:00 CST 2019
     */
    private String majorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_class.xuezhi
     *
     * @mbg.generated Sat May 04 18:49:00 CST 2019
     */
    private String xuezhi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_class.class_id
     *
     * @mbg.generated Sat May 04 18:49:00 CST 2019
     */
    private String classId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_class.people_num
     *
     * @return the value of major_class.people_num
     *
     * @mbg.generated Sat May 04 18:49:00 CST 2019
     */
    public String getPeopleNum() {
        return peopleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_class.people_num
     *
     * @param peopleNum the value for major_class.people_num
     *
     * @mbg.generated Sat May 04 18:49:00 CST 2019
     */
    public void setPeopleNum(String peopleNum) {
        this.peopleNum = peopleNum == null ? null : peopleNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_class.major_name
     *
     * @return the value of major_class.major_name
     *
     * @mbg.generated Sat May 04 18:49:00 CST 2019
     */
    public String getMajorName() {
        return majorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_class.major_name
     *
     * @param majorName the value for major_class.major_name
     *
     * @mbg.generated Sat May 04 18:49:00 CST 2019
     */
    public void setMajorName(String majorName) {
        this.majorName = majorName == null ? null : majorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_class.xuezhi
     *
     * @return the value of major_class.xuezhi
     *
     * @mbg.generated Sat May 04 18:49:00 CST 2019
     */
    public String getXuezhi() {
        return xuezhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_class.xuezhi
     *
     * @param xuezhi the value for major_class.xuezhi
     *
     * @mbg.generated Sat May 04 18:49:00 CST 2019
     */
    public void setXuezhi(String xuezhi) {
        this.xuezhi = xuezhi == null ? null : xuezhi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_class.class_id
     *
     * @return the value of major_class.class_id
     *
     * @mbg.generated Sat May 04 18:49:00 CST 2019
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_class.class_id
     *
     * @param classId the value for major_class.class_id
     *
     * @mbg.generated Sat May 04 18:49:00 CST 2019
     */
    public void setClassId(String classId) {
        this.classId = classId == null ? null : classId.trim();
    }
}