package com.example.school_system.demo.pojo;

public class Major {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.major_name
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    private String majorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.id
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.people_num
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    private String peopleNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.academy_name
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    private String academyName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.major_name
     *
     * @return the value of major.major_name
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    public String getMajorName() {
        return majorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.major_name
     *
     * @param majorName the value for major.major_name
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    public void setMajorName(String majorName) {
        this.majorName = majorName == null ? null : majorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.id
     *
     * @return the value of major.id
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.id
     *
     * @param id the value for major.id
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.people_num
     *
     * @return the value of major.people_num
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    public String getPeopleNum() {
        return peopleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.people_num
     *
     * @param peopleNum the value for major.people_num
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    public void setPeopleNum(String peopleNum) {
        this.peopleNum = peopleNum == null ? null : peopleNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.academy_name
     *
     * @return the value of major.academy_name
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    public String getAcademyName() {
        return academyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.academy_name
     *
     * @param academyName the value for major.academy_name
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    public void setAcademyName(String academyName) {
        this.academyName = academyName == null ? null : academyName.trim();
    }
}