package com.example.school_system.demo.pojo;

public class MajorClassKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_class.id
     *
     * @mbg.generated Sat May 04 18:49:00 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_class.class_name
     *
     * @mbg.generated Sat May 04 18:49:00 CST 2019
     */
    private String className;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_class.id
     *
     * @return the value of major_class.id
     *
     * @mbg.generated Sat May 04 18:49:00 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_class.id
     *
     * @param id the value for major_class.id
     *
     * @mbg.generated Sat May 04 18:49:00 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_class.class_name
     *
     * @return the value of major_class.class_name
     *
     * @mbg.generated Sat May 04 18:49:00 CST 2019
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_class.class_name
     *
     * @param className the value for major_class.class_name
     *
     * @mbg.generated Sat May 04 18:49:00 CST 2019
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }
}