package com.example.school_system.demo.pojo;

public class MajorClass {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_class.class_name
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_class.id
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_class.people_name
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    private String peopleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_class.major_name
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    private String majorName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_class.class_name
     *
     * @return the value of major_class.class_name
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_class.class_name
     *
     * @param className the value for major_class.class_name
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_class.id
     *
     * @return the value of major_class.id
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_class.id
     *
     * @param id the value for major_class.id
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_class.people_name
     *
     * @return the value of major_class.people_name
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    public String getPeopleName() {
        return peopleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_class.people_name
     *
     * @param peopleName the value for major_class.people_name
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    public void setPeopleName(String peopleName) {
        this.peopleName = peopleName == null ? null : peopleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_class.major_name
     *
     * @return the value of major_class.major_name
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    public String getMajorName() {
        return majorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_class.major_name
     *
     * @param majorName the value for major_class.major_name
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    public void setMajorName(String majorName) {
        this.majorName = majorName == null ? null : majorName.trim();
    }
}