package com.example.school_system.demo.pojo;

public class PreSelectCourseTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_select_course_task.id
     *
     * @mbg.generated Tue Apr 16 20:45:42 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_select_course_task.academy_name
     *
     * @mbg.generated Tue Apr 16 20:45:42 CST 2019
     */
    private String academyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_select_course_task.major_name
     *
     * @mbg.generated Tue Apr 16 20:45:42 CST 2019
     */
    private String majorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_select_course_task.class_name
     *
     * @mbg.generated Tue Apr 16 20:45:42 CST 2019
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_select_course_task.course_id
     *
     * @mbg.generated Tue Apr 16 20:45:42 CST 2019
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_select_course_task.time
     *
     * @mbg.generated Tue Apr 16 20:45:42 CST 2019
     */
    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_select_course_task.id
     *
     * @return the value of pre_select_course_task.id
     *
     * @mbg.generated Tue Apr 16 20:45:42 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_select_course_task.id
     *
     * @param id the value for pre_select_course_task.id
     *
     * @mbg.generated Tue Apr 16 20:45:42 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_select_course_task.academy_name
     *
     * @return the value of pre_select_course_task.academy_name
     *
     * @mbg.generated Tue Apr 16 20:45:42 CST 2019
     */
    public String getAcademyName() {
        return academyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_select_course_task.academy_name
     *
     * @param academyName the value for pre_select_course_task.academy_name
     *
     * @mbg.generated Tue Apr 16 20:45:42 CST 2019
     */
    public void setAcademyName(String academyName) {
        this.academyName = academyName == null ? null : academyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_select_course_task.major_name
     *
     * @return the value of pre_select_course_task.major_name
     *
     * @mbg.generated Tue Apr 16 20:45:42 CST 2019
     */
    public String getMajorName() {
        return majorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_select_course_task.major_name
     *
     * @param majorName the value for pre_select_course_task.major_name
     *
     * @mbg.generated Tue Apr 16 20:45:42 CST 2019
     */
    public void setMajorName(String majorName) {
        this.majorName = majorName == null ? null : majorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_select_course_task.class_name
     *
     * @return the value of pre_select_course_task.class_name
     *
     * @mbg.generated Tue Apr 16 20:45:42 CST 2019
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_select_course_task.class_name
     *
     * @param className the value for pre_select_course_task.class_name
     *
     * @mbg.generated Tue Apr 16 20:45:42 CST 2019
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_select_course_task.course_id
     *
     * @return the value of pre_select_course_task.course_id
     *
     * @mbg.generated Tue Apr 16 20:45:42 CST 2019
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_select_course_task.course_id
     *
     * @param courseId the value for pre_select_course_task.course_id
     *
     * @mbg.generated Tue Apr 16 20:45:42 CST 2019
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_select_course_task.time
     *
     * @return the value of pre_select_course_task.time
     *
     * @mbg.generated Tue Apr 16 20:45:42 CST 2019
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_select_course_task.time
     *
     * @param time the value for pre_select_course_task.time
     *
     * @mbg.generated Tue Apr 16 20:45:42 CST 2019
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }
}