package com.example.school_system.demo.pojo;

import java.util.Date;

public class SensitiveOperation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_operation.id
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_operation.
operator_name
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    private String 
operatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_operation.time
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_operation.action
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    private String action;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_operation.id
     *
     * @return the value of sensitive_operation.id
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_operation.id
     *
     * @param id the value for sensitive_operation.id
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_operation.
operator_name
     *
     * @return the value of sensitive_operation.
operator_name
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    public String getoperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_operation.
operator_name
     *
     * @param 
operatorName the value for sensitive_operation.
operator_name
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    public void setoperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_operation.time
     *
     * @return the value of sensitive_operation.time
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_operation.time
     *
     * @param time the value for sensitive_operation.time
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_operation.action
     *
     * @return the value of sensitive_operation.action
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_operation.action
     *
     * @param action the value for sensitive_operation.action
     *
     * @mbg.generated Tue Mar 19 16:34:36 CST 2019
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }
}