package com.example.school_system.demo.pojo;

public class StudentScore {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.id
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.course
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    private String course;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.course_type
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    private String courseType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.student_id
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.usual_score
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    private String usualScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.exam_score
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    private String examScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.total_score
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    private String totalScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.credit
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    private String credit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.GPA
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    private String gpa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.credit&GPA
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    private String creditGpa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.term
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    private String term;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.id
     *
     * @return the value of student_score.id
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.id
     *
     * @param id the value for student_score.id
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.course
     *
     * @return the value of student_score.course
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    public String getCourse() {
        return course;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.course
     *
     * @param course the value for student_score.course
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    public void setCourse(String course) {
        this.course = course == null ? null : course.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.course_type
     *
     * @return the value of student_score.course_type
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    public String getCourseType() {
        return courseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.course_type
     *
     * @param courseType the value for student_score.course_type
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    public void setCourseType(String courseType) {
        this.courseType = courseType == null ? null : courseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.student_id
     *
     * @return the value of student_score.student_id
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.student_id
     *
     * @param studentId the value for student_score.student_id
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.usual_score
     *
     * @return the value of student_score.usual_score
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    public String getUsualScore() {
        return usualScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.usual_score
     *
     * @param usualScore the value for student_score.usual_score
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    public void setUsualScore(String usualScore) {
        this.usualScore = usualScore == null ? null : usualScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.exam_score
     *
     * @return the value of student_score.exam_score
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    public String getExamScore() {
        return examScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.exam_score
     *
     * @param examScore the value for student_score.exam_score
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    public void setExamScore(String examScore) {
        this.examScore = examScore == null ? null : examScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.total_score
     *
     * @return the value of student_score.total_score
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    public String getTotalScore() {
        return totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.total_score
     *
     * @param totalScore the value for student_score.total_score
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    public void setTotalScore(String totalScore) {
        this.totalScore = totalScore == null ? null : totalScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.credit
     *
     * @return the value of student_score.credit
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    public String getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.credit
     *
     * @param credit the value for student_score.credit
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    public void setCredit(String credit) {
        this.credit = credit == null ? null : credit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.GPA
     *
     * @return the value of student_score.GPA
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    public String getGpa() {
        return gpa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.GPA
     *
     * @param gpa the value for student_score.GPA
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    public void setGpa(String gpa) {
        this.gpa = gpa == null ? null : gpa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.credit&GPA
     *
     * @return the value of student_score.credit&GPA
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    public String getCreditGpa() {
        return creditGpa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.credit&GPA
     *
     * @param creditGpa the value for student_score.credit&GPA
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    public void setCreditGpa(String creditGpa) {
        this.creditGpa = creditGpa == null ? null : creditGpa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.term
     *
     * @return the value of student_score.term
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    public String getTerm() {
        return term;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.term
     *
     * @param term the value for student_score.term
     *
     * @mbg.generated Mon Apr 08 22:36:09 CST 2019
     */
    public void setTerm(String term) {
        this.term = term == null ? null : term.trim();
    }
}