package com.example.school_system.demo.pojo;

public class SystemError {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_error.id
     *
     * @mbg.generated Thu May 09 11:50:49 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_error.class_name
     *
     * @mbg.generated Thu May 09 11:50:49 CST 2019
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_error.method_name
     *
     * @mbg.generated Thu May 09 11:50:49 CST 2019
     */
    private String methodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_error.message
     *
     * @mbg.generated Thu May 09 11:50:49 CST 2019
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_error.time
     *
     * @mbg.generated Thu May 09 11:50:49 CST 2019
     */
    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_error.id
     *
     * @return the value of system_error.id
     *
     * @mbg.generated Thu May 09 11:50:49 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_error.id
     *
     * @param id the value for system_error.id
     *
     * @mbg.generated Thu May 09 11:50:49 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_error.class_name
     *
     * @return the value of system_error.class_name
     *
     * @mbg.generated Thu May 09 11:50:49 CST 2019
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_error.class_name
     *
     * @param className the value for system_error.class_name
     *
     * @mbg.generated Thu May 09 11:50:49 CST 2019
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_error.method_name
     *
     * @return the value of system_error.method_name
     *
     * @mbg.generated Thu May 09 11:50:49 CST 2019
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_error.method_name
     *
     * @param methodName the value for system_error.method_name
     *
     * @mbg.generated Thu May 09 11:50:49 CST 2019
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName == null ? null : methodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_error.message
     *
     * @return the value of system_error.message
     *
     * @mbg.generated Thu May 09 11:50:49 CST 2019
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_error.message
     *
     * @param message the value for system_error.message
     *
     * @mbg.generated Thu May 09 11:50:49 CST 2019
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_error.time
     *
     * @return the value of system_error.time
     *
     * @mbg.generated Thu May 09 11:50:49 CST 2019
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_error.time
     *
     * @param time the value for system_error.time
     *
     * @mbg.generated Thu May 09 11:50:49 CST 2019
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }
}