package com.example.school_system.demo.pojo;

public class TeacherMsg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_msg.id
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_msg.name
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_msg.sex
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_msg.jiguan
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    private String jiguan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_msg.nation
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    private String nation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_msg.zz_face
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    private String zzFace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_msg.birth_day
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    private String birthDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_msg.marital status
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    private String maritalStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_msg.health_condition
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    private String healthCondition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_msg.education
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_msg.huji_addr
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    private String hujiAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_msg.id_num
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    private String idNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_msg.addr
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_msg.tel
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    private String tel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_msg.id
     *
     * @return the value of teacher_msg.id
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_msg.id
     *
     * @param id the value for teacher_msg.id
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_msg.name
     *
     * @return the value of teacher_msg.name
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_msg.name
     *
     * @param name the value for teacher_msg.name
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_msg.sex
     *
     * @return the value of teacher_msg.sex
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_msg.sex
     *
     * @param sex the value for teacher_msg.sex
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_msg.jiguan
     *
     * @return the value of teacher_msg.jiguan
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public String getJiguan() {
        return jiguan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_msg.jiguan
     *
     * @param jiguan the value for teacher_msg.jiguan
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public void setJiguan(String jiguan) {
        this.jiguan = jiguan == null ? null : jiguan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_msg.nation
     *
     * @return the value of teacher_msg.nation
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_msg.nation
     *
     * @param nation the value for teacher_msg.nation
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_msg.zz_face
     *
     * @return the value of teacher_msg.zz_face
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public String getZzFace() {
        return zzFace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_msg.zz_face
     *
     * @param zzFace the value for teacher_msg.zz_face
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public void setZzFace(String zzFace) {
        this.zzFace = zzFace == null ? null : zzFace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_msg.birth_day
     *
     * @return the value of teacher_msg.birth_day
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public String getBirthDay() {
        return birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_msg.birth_day
     *
     * @param birthDay the value for teacher_msg.birth_day
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public void setBirthDay(String birthDay) {
        this.birthDay = birthDay == null ? null : birthDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_msg.marital status
     *
     * @return the value of teacher_msg.marital status
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public String getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_msg.marital status
     *
     * @param maritalStatus the value for teacher_msg.marital status
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus == null ? null : maritalStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_msg.health_condition
     *
     * @return the value of teacher_msg.health_condition
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public String getHealthCondition() {
        return healthCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_msg.health_condition
     *
     * @param healthCondition the value for teacher_msg.health_condition
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public void setHealthCondition(String healthCondition) {
        this.healthCondition = healthCondition == null ? null : healthCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_msg.education
     *
     * @return the value of teacher_msg.education
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_msg.education
     *
     * @param education the value for teacher_msg.education
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_msg.huji_addr
     *
     * @return the value of teacher_msg.huji_addr
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public String getHujiAddr() {
        return hujiAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_msg.huji_addr
     *
     * @param hujiAddr the value for teacher_msg.huji_addr
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public void setHujiAddr(String hujiAddr) {
        this.hujiAddr = hujiAddr == null ? null : hujiAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_msg.id_num
     *
     * @return the value of teacher_msg.id_num
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public String getIdNum() {
        return idNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_msg.id_num
     *
     * @param idNum the value for teacher_msg.id_num
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public void setIdNum(String idNum) {
        this.idNum = idNum == null ? null : idNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_msg.addr
     *
     * @return the value of teacher_msg.addr
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_msg.addr
     *
     * @param addr the value for teacher_msg.addr
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_msg.tel
     *
     * @return the value of teacher_msg.tel
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_msg.tel
     *
     * @param tel the value for teacher_msg.tel
     *
     * @mbg.generated Sun Mar 17 18:47:04 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }
}